---
version: "3.9"

services:
  ude-router:
    image: nginx:1.20.2-alpine
    environment:
      - UDE_BASE_DOMAIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ude-router/nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./static:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs

networks:
  default:
    name: ${UDE_NETWORK_NAME:-universal-devenv}
